# Generated by Django 4.1.7 on 2023-03-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booklist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="book_title", new_name="title",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default="unnamed", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(default="default", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="wordcount",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
