# Generated by Django 4.1.7 on 2023-03-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "booklist",
            "0002_rename_book_title_book_title_book_author_book_genre_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=200)),
                ("content", models.CharField(max_length=5000)),
                ("publish_date", models.DateTimeField(verbose_name="date published")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booklist.book"
                    ),
                ),
            ],
        ),
    ]
